### PR TITLE
Expand release

### PR DESCRIPTION
**Pull request by jburel**
This PR 
* add the java version to the name of the zip/tar
* attaches all the artifacts to the release

### CODE REVIEW

**Comment by jburel** [comment]
@khaledk2 changes tested via https://github.com/jburel/omero-ms-image-region/releases/tag/2024.07.17

**Comment by khaledk2** [comment]
I think the folder name inside the compressed file should have the same name as the file.
For example, the folder should be  `\omero-ms-image-region-0.10.0_11 `inside `\omero-ms-image-region-0.10.0_11.zip `
it is now `\omero-ms-image-region-0.10.0`

**Comment by jburel** [comment]
That will mean unzipping, changing the name and re-zipping. This not what is currently done during the build process i.e. see for example https://github.com/ome/omero-ms-image-region/actions/runs/9954646655, check the folder name and the zip name.
The appended version is mainly to make sure that one selects the zip matching the Java version installed.

**Comment by khaledk2** [comment]
This should be fine,  but we should update https://github.com/ome/ansible-role-omero-ms-image-region/pull/4 to account for that.

**Review by khaledk2 — APPROVED** [review]

**Pull request merged**
